sample: chr19
samplename: XXX
truth: ../Files_needed_for_task/ground_truth.vcf
target: ../Files_needed_for_task/target_regions.bed
caller_file: data/variant_callers.tsv

dbSNP:
  # download site
  site: https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/common_all_20180423.vcf.gz
  # save download to
  path: data/common_all_20180423.vcf.gz
  # chromosome of interest
  chr: 19

ref:
  # download from site
  site: rsync://hgdownload.soe.ucsc.edu/goldenPath/hg19/chromosomes/chr19.fa.gz
  complete: rsync://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz
  # 2bit: rsync://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.2bit
  # ensembl release
  version: GRCh37.87
  release: hg19
  # region of interest
  reg: 19:60677-14992498

picard_config:
  HsMetrics_table_cols:
    - NEAR_BAIT_BASES
    - ON_BAIT_BASES
    - MEAN_TARGET_COVERAGE
    - ON_BAIT_VS_SELECTED
    - MEDIAN_TARGET_COVERAGE
    - ZERO_CVG_TARGETS_PCT
    - PCT_EXC_OFF_TARGET
    - PCT_TARGET_BASES_10X
    - PCT_TARGET_BASES_30X
    - PCT_TARGET_BASES_100X
    - AT_DROPOUT
    - GC_DROPOUT
  HsMetrics_table_cols_hidden:
    - MAX_TARGET_COVERAGE
    - MEAN_BAIT_COVERAGE
    - OFF_BAIT_BASES

modules:
  r: envs/r-envir/bin/Rscript
  bcf: envs/var_call_v1/bin/bcftools
  snpeff: envs/var_call_v1/share/snpeff-5.0-0/snpEff.jar
  variant_caller: gatk

filters:
  bcf: '%QUAL<20 || (AC<2 && %QUAL<15) || %MAX(AD)<=10 || %MAX(AD)/%MAX(INFO/DP)<=0.5 || %MAX(INFO/DP)>300'